### Создать сотрудника 1
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "nameFirst",
  "lastName": "fNFirst",
  "department": 1,
  "salary": 1200
}

### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "nameSecond",
  "lastName": "fNSecond",
  "department": 2,
  "salary": 1300
}

### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "nameThird",
  "lastName": "fNThird",
  "department": 3,
  "salary": 1400
}

### Создать сотрудника 4
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "nameForth",
  "lastName": "fNForth",
  "department": 4,
  "salary": 1500
}



### Создать сотрудника 5
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "nameFifth",
  "lastName": "fNFifth",
  "department": 5,
  "salary": 1600
}

### Создать сотрудника 6
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "nameSixth",
  "lastName": "fNSixth",
  "department": 1,
  "salary": 1100
}

### Создать сотрудника 7
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "nameSeventh",
  "lastName": "fNSeventh",
  "department": 2,
  "salary": 1700
}

### Создать сотрудника 8
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "nameEighth",
  "lastName": "fNEighth",
  "department": 3,
  "salary": 1800
}

### Создать сотрудника 9
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "nameNinth",
  "lastName": "fNNinth",
  "department": 4,
  "salary": 2000
}



### Создать сотрудника 10
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "nameTenth",
  "lastName": "fNTenth",
  "department": 5,
  "salary": 1900
}